<h1>Books</h1>
<b><?=\Library\Session::getFlash()?></b>
<div class="table-responsive">
<table width="100%" border="1" class="table">
    <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Price</th>
        <th>Status</th>
        <th>Actions</th>
    </tr>

<?php foreach ($books as $book): ?>
    <tr>
        <td><?=$book['id']?></td>
        <td><?=$book['title']?></td>
        <td><?=$book['price']?></td>
        <td><?=$book['status']?></td>
        <td>
            <a href="/admin/books/edit/<?=$book['id']?>">Edit</a>
            <a href="/admin/delete/<?=$book['id']?>" onclick="return confirm('Are you sure')">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>

</table>
</div>