<h1>Welcome</h1>

<script>
    var a = 1;
    function test() {
        var a, b, c = 'hello';
        var student = {
            name: 'Mike',
            age: 23,
            city: 'Hamburg',
            status: false,

            study: function() {
                console.log('Study php');
            }
        };

        student.study();
    }



</script>

<span onclick="this.style.display='none'"><?=$number?></span>



<br>

<a href="http://google.com" id="hello"><?=$name?></a>


<br><br><br>
<button type="button">Ajax</button>
<div id="test">

</div>

<script>
    $('button').click(function(){
//        $.get('/bla-bla-ajax?a=21&b=2', function(data) {
//            var books = JSON.parse(data);
//            for (key in books) {
//                $('#test').append(books[key].title + '<br>');
//            }
//        });

        $.post('/post-ajax', {bla: 'new style'}, function(data) {
            alert(data);
        });

    });



//    var a = 1, b, c = 'hello';
//    var student = {
//        name: 'Mike',
//        age: 23,
//        city: 'Hamburg',
//        status: false,
//
//        study: function() {
//            console.log('Study php');
//        }
//    };
//
//
//    var elements = document.getElementsByTagName('div');
    console.log(elements);
   // console.log(element.);
   // console.log(document);
    // Number, String, Boolean, Array, Object
</script>