<h1>Books</h1>

<div class="row">

<?php foreach ($books as $book): ?>
    <div class="book-item col-md-3 col-lg-2 col-sm-6 col-xs-12">
        <div>
            Title: <?=$book['title']?><br>
            Author:<?=$book['authors']?> <br>
            Price: <?=$book['price']?><br>

            <a href="/book-<?=$book['id']?>.html">Details</a>
        </div>
        <button type="button" class="btn btn-default">Test</button>
        <img src="/uploads/cat.jpg" alt="" class="img-responsive">
    </div>
<?php endforeach; ?>

</div>

<script>
    $('button').click(function() {
        alert($(this).parent().children().first().html());
    });

//    var elements = document.getElementsByTagName('div');
//    for (key in elements) {
//        elements[key].style.display = 'None';
//    }


</script>
