<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=MetaHelper::getTitle();?></title>
</head>
<body>
<a href="/">Main</a>
<a href="/books">Books</a>
<a href="/contact-us">Contact</a>
|
<?php if (!Session::has('user')) : ?>
    <a href="/login">Login</a>
<?php else: ?>
    <a href="/logout">Logout</a>
<?php endif?>
<hr>
<?=$content ?>
<br>
<br>
<br>
<br>
<br>
<hr>
All rights reserved &copy; 2016
</body>
</html>